const detalles = [
    {id: "1", 
        nombre: "PRODUCTO 1", 
        img: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Wallpaper.jpg", 
        img2: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Computer-Wallpaper.jpg", 
        img3: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Desktop-Wallpaper.jpg", 
        precio: 1200, 
        stock: 3, 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur", 
        categoria: "Agendas", 
        minDescripcion: "Agendas 2022"},
    {id: "2", 
        nombre: "PRODUCTO 2", 
        img: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Wallpaper.jpg", 
        img2: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Computer-Wallpaper.jpg", 
        img3: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Desktop-Wallpaper.jpg", 
        precio: 1200, 
        stock: 4, 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur", 
        categoria: "Agendas", 
        minDescripcion: "Agendas 2022"},
    {id: "3", 
        nombre: "PRODUCTO 3", 
        img: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Wallpaper.jpg", 
        img2: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Computer-Wallpaper.jpg", 
        img3: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Desktop-Wallpaper.jpg", 
        precio: 1900, 
        stock: 6, 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur", 
        categoria: "Agendas", 
        minDescripcion: "Agendas 2022"},
    {id: "4", 
        nombre: "PRODUCTO 4", 
        img: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Wallpaper.jpg", 
        img2: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Computer-Wallpaper.jpg", 
        img3: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Desktop-Wallpaper.jpg", 
        precio: 1400, 
        stock: 7, 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur", 
        categoria: "Cuadernos", 
        minDescripcion: "Cuadernos hoja lisa"},
    {id: "5", 
        nombre: "PRODUCTO 5", 
        img: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Wallpaper.jpg", 
        img2: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Computer-Wallpaper.jpg", 
        img3: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Desktop-Wallpaper.jpg",
        precio: 1300, 
        stock: 1, 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur", 
        categoria: "Cuadernos", 
        minDescripcion: "Cuadernos hoja lisa"},
    {id: "6", 
        nombre: "PRODUCTO 6", 
        img: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Wallpaper.jpg", 
        img2: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Computer-Wallpaper.jpg", 
        img3: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Desktop-Wallpaper.jpg",
        precio: 1000, 
        stock: 9, 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur", 
        categoria: "Cuadernos", 
        minDescripcion: "Cuadernos hoja lisa"},
    {id: "7", 
        nombre: "PRODUCTO 7", 
        img: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Wallpaper.jpg", 
        img2: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Computer-Wallpaper.jpg", 
        img3: "https://mypcwalls.com/wp-content/uploads/2021/08/minimalist-Desktop-Wallpaper.jpg", 
        precio: 1250, 
        stock: 5, 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur", 
        categoria: "Agendas", 
        minDescripcion: "Agendas 2022"}
]

const getProductsDetail = new Promise ((res, rej) => {
    setTimeout(() => {
        res(detalles)
    }, 2000);
}) 

export default getProductsDetail